# Generated by Django 5.1.5 on 2025-04-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='pack',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='card',
            name='tier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_image_url',
            field=models.URLField(),
        ),
    ]
