# Generated by Django 5.1.5 on 2025-04-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_card_name_card_pack_card_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='uid',
            field=models.TextField(),
        ),
    ]
