# Generated by Django 5.1.5 on 2025-04-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_card_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedby',
            name='count',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
