# Generated by Django 5.1.5 on 2025-04-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_ownedby_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='tier',
        ),
    ]
