# Generated by Django 5.1.5 on 2025-04-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_card_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='uid',
            field=models.TextField(default=''),
        ),
    ]
