# Generated by Django 5.1.5 on 2025-04-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_pocketfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='poke_type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
