# Generated by Django 5.1.5 on 2025-04-22 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_card_card_type_card_poke_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='booster',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
