# Generated by Django 5.1.5 on 2025-04-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_card_booster'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
