# Generated by Django 5.1.5 on 2025-04-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_card_rarity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='uid',
            new_name='cid',
        ),
    ]
