# Generated by Django 5.1.5 on 2025-04-28 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_rename_uid_card_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('sender_accept', models.BooleanField(blank=True, default=False)),
                ('receiver_accept', models.BooleanField(blank=True, default=False)),
                ('card1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_card', to='project.ownedby')),
                ('card2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_card', to='project.ownedby')),
                ('profile1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_sender', to='project.pocketprofile')),
                ('profile2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_receiver', to='project.pocketprofile')),
            ],
        ),
    ]
