# Generated by Django 5.1.5 on 2025-04-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_traderequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderequest',
            name='card2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_card', to='project.ownedby'),
        ),
    ]
