# Generated by Django 5.1.5 on 2025-04-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_traderequest_card2'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='canceled',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
