# Generated by Django 5.1.5 on 2025-04-28 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_traderequest_canceled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traderequest',
            old_name='receiver_accept',
            new_name='rcv_acc',
        ),
        migrations.RenameField(
            model_name='traderequest',
            old_name='sender_accept',
            new_name='send_acc',
        ),
    ]
