# Generated by Django 5.1.5 on 2025-04-30 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_pocketfriendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pocketfriendrequest',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
