# Generated by Django 5.1.5 on 2025-05-01 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_rename_created_at_pocketfriendrequest_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.pocketprofile')),
            ],
        ),
    ]
