# Generated by Django 5.1.5 on 2025-05-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='profile',
        ),
    ]
