# Generated by Django 5.1.5 on 2025-03-07 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusimage',
            name='status_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mini_fb.statusmessage'),
        ),
    ]
